### PR TITLE
Add optional realism example, comments.

### PR DESCRIPTION
**Pull request by Vladimir-csp**

### CODE REVIEW

**Comment by peteletroll** [comment]
I'll probably include your request as a separate cfg file, if you're OK with that. Something like DockRotate-Realism.cfg

**Comment by Vladimir-csp** [comment]
OK.

**Comment by peteletroll** [comment]
Your request seems very specific, I don't know how many players are interested: that's why I have some doubts about inhibiting the rotation commands when snapRotation is true. Is this something interesting to Realism Overhaul players?

**Comment by Vladimir-csp** [comment]
I do not know, it might.
If there were an option in ModuleDockRotate to turn controls on/off, it would be more versatile. It would be possible to tie it (or not) to ModuleDockingNode/snapRotation in an MM patch.

**Pull request merged**
