### PR TITLE
dictionary-es-es.cfg

### PR DESCRIPTION
**Pull request by Fitiales**
info localization

### CODE REVIEW

**Comment by Fitiales** [comment]
Sorry.

I've left almost half for an error when copying

**Comment by peteletroll** [comment]
Hi Fitiales, I added a #DCKROT_stop_rotation entry to the dictionaries. Could you please translate it to Spanish?
Thanks in advance.

**Comment by Fitiales** [comment]
Done!

**Comment by peteletroll** [comment]
Thanks! But I can't see your update on github. Maybe you didn't push?

**Comment by Fitiales** [comment]
Oh! sorry.
I forgot to click the button a second time.

**Comment by peteletroll** [comment]
I suppose I should correct "Detener ro**a**tación" to "Detener rotación".

**Pull request merged**
